# These are the styles for syntax highlighting

"type" = "blue1"
"constructor" = "magenta"

"constant" = "orange"
# "constant.builtin" = 
# "constant.builtin.boolean" = 
"constant.character" = "green"
"constant.character.escape" = "magenta" 
# "constant.numeric" = 
# "constant.numeric.integer" = 
# "constant.numeric.float" = 

"string" = "green"
"string.regexp" = "blue6"
"string.special" = "blue1"
# "string.special.path" = 

"comment" = "comment"
# "comment.line" = 
# "comment.block" = 
# "comment.block.documentation" = 

"variable" = "magenta"
"variable.builtin" = "red"
"variable.parameter" = "yellow"
# "variable.other" = 
# "variable.other.member" = 
# "variable.function" = 

"label" = "blue"

"punctuation" = "blue5"
"punctuation.delimeter" = "blue5" 

"keyword" = {fg = "cyan", modifiers = ["italic"] }
# "keyword.control.repeat" = 
# "keyword.control.import" = 
# "keyword.control.return" = 
# "keyword.control.exception" = 
# "keyword.operator" = 
# "keyword.directive" = 
"keyword.function" = "magenta" 

"operator" = "blue5"

# "function.macro" = 
# "function.special" = 

"tag" = "red"
# "namespace" = 

"markup" = "blue"
"markup.heading" = "orange"
# "markup.heading.marker" = 
"markup.heading.1" = { fg = "magenta", modifiers = ["bold"] }
"markup.heading.2" = { modifiers = ["bold"] }
# "markup.heading.3" = 
# "markup.heading.4" = 
# "markup.heading.5" = 
# "markup.heading.6" = 
# "markup.list" = 
# "markup.list.unnumbered" = 
# "markup.list.numbered" = 
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] } 
# "markup.link" = 
# "markup.link.url" = 
# "markup.link.label" = 
"markup.link.text" = { modifiers = ["underlined"] }
# "markup.quote" = 
"markup.raw" = "teal"
# "markup.raw.inline" = 
# "markup.raw.block" = 

"diff" = "blue7"
"diff.plus" = "#283B4D"
"diff.minus" = "#3F2D3D" 
"diff.delta" = "#272D43"
# "diff.delta.moved" = 

#These styles affect editor interface

# "markup" = 
# "markup.normal" = 
"markup.normal.completion" = "teal" 
"markup.normal.hover" = "teal"
# "markup.heading" = 
"markup.heading.completion" = "teal"
"markup.heading.hover" = "teal"
# "markup.raw" = 
# "markup.raw.inline" = 
# "markup.raw.inline.completion" = 
# "markup.raw.inline.hover" = 

"ui.background" = "bg"
"ui.cursor" = { fg = "bg", bg = "fg" }
# "ui.cursor.insert" = 
"ui.cursor.select" = "bg_visual"
"ui.cursor.match" = { fg = "fg_dark", bg = "orange" }
# "ui.cursor.primary" = 
"ui.statusline" = { fg = "fg_sidebar", bg = "bg_statusline" }
"ui.text" = "fg"
# "ui.text.focus" = 
# "ui.text.info" = 
"ui.menu" = { fg = "fg", bg = "bg_float" }
"ui.menu.selected" = { bg = "#363D59"}
"ui.selection" = { bg = "bg_visual" }
# "ui.selection.primary" =  

"warning" = "yellow"
"error" = "red1"
"info" = "blue2"
"hint" = "teal"
"diagnostic" = { modifiers = ["underlined"] }

[palette]
bg = "#24283b"
bg_visual = "#364A82"
fg = "#c0caf5"
fg_dark = "#a9b1d6"
fg_gutter = "#3b4261"
comment = "#565f89"
blue = "#7aa2f7"
cyan = "#7dcfff"
blue1 = "#2ac3de"
blue2 = "#0db9d7"
blue5 = "#89ddff"
blue6 = "#B4F9F8"
blue7 = "#394b70"
magenta = "#bb9af7"
orange = "#ff9e64"
yellow = "#e0af68"
green = "#9ece6a"
teal = "#1abc9c"
red = "#f7768e"
red1 = "#db4b4b"