# These are the styles for syntax highlighting

type = "blue1"
constructor = "magenta"

constant = "orange"
constant.builtin = 
constant.builtin.boolean = 
constant.character = 
constant.character.escape = 
constant.numeric = 
constant.numeric.integer = 
constant.numeric.float = 

string = 
string.regexp = 
string.special = 
string.special.path = 
string.special.url = 
string.special.symbol = 

comment = 
comment.line = 
comment.block = 
comment.block.documentation = 

variable = 
variable.builtin = 
variable.parameter = 
variable.other = 
variable.other.member = 
variable.function = 

label = 

punctuation = 
punctuation.delimeter = 
punctuation.bracket = 

keyword = 
keyword.control = 
keyword.control.conditional = 
keyword.control.repeat = 
keyword.control.import = 
keyword.control.return = 
keyword.control.exception = 
keyword.operator = 
keyword.directive = 
keyword.function = 

operator

function = 
function.builtin = 
function.method = 
function.macro = 
function.special = 

tag = 
namespace = 

markup = 
markup.heading = 
markup.heading.marker = 
markup.heading.1 = 
markup.heading.2 = 
markup.heading.3 = 
markup.heading.4 = 
markup.heading.5 = 
markup.heading.6 = 
markup.list = 
markup.list.unnumbered = 
markup.list.numbered = 
markup.bold = 
markup.italic = 
markup.link = 
markup.link.url = 
markup.link.label = 
markup.link.text = 
markup.quote = 
markup.raw = 
markup.raw.inline = 
markup.raw.block = 

diff = 
diff.plus = 
diff.minus = 
diff.delta = 
diff.delta.moved = 

#These styles affect editor interface

markup = 
markup.normal = 
markup.normal.completion = 
markup.normal.hover = 
markup.heading = 
markup.heading.completion = 
markup.heading.hover = 
markup.raw = 
markup.raw.inline = 
markup.raw.inline.completion = 
markup.raw.inline.hover = 

ui.background = 
ui.cursor = 
ui.cursor.insert = 
ui.cursor.select = 
ui.cursor.match = 
ui.cursor.primary = 
ui.linenr = 
ui.linenr.selected = 
ui.statusline = 
ui.statusline.inactive = 
ui.popup = 
ui.popup.info = 
ui.window = 
ui.help = 
ui.text = 
ui.text.focus = 
ui.text.info = 
ui.menu = 
ui.menu.selected = 
ui.selection = 
ui.selection.primary = 

warning = 
error = 
info = 
hint = 
diagnostic = 

[palette]
none = "NONE"
bg_dark = "#1f2335"
bg = "#24283b"
bg_highlight = "#292e42"
terminal_black = "#414868"
fg = "#c0caf5"
fg_dark = "#a9b1d6"
fg_gutter = "#3b4261"
dark3 = "#545c7e"
comment = "#565f89"
dark5 = "#737aa2"
blue0 = "#3d59a1"
blue = "#7aa2f7"
cyan = "#7dcfff"
blue1 = "#2ac3de"
blue2 = "#0db9d7"
blue5 = "#89ddff"
blue6 = "#B4F9F8"
blue7 = "#394b70"
magenta = "#bb9af7"
magenta2 = "#ff007c"
purple = "#9d7cd8"
orange = "#ff9e64"
yellow = "#e0af68"
green = "#9ece6a"
green1 = "#73daca"
green2 = "#41a6b5"
teal = "#1abc9c"
red = "#f7768e"
red1 = "#db4b4b"
git.change = "#6183bb"
git.add = "#449dab"
git.delete = "#914c54"
git.conflict = "#bb7a61"
gitSigns.add = "#164846"
gitSigns.change = "#394b70"
gitSigns.delete = "#823c41"